#Values for myservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

basechart:
  replicaCount:
    prod:
      us-east-1: 1
  containers:
    forter-gist:
      image: "forter-gist"
      imagePullPolicy: Always
      command:
        - "/opengist/docker/entrypoint.sh"
      env:
        - name: OG_OIDC_CLIENT_KEY
          value: "0oa16fpecokgXm9fA0x8"
        - name: OG_OPENGIST_HOME
          value: "/opengist"
        - name: OG_OIDC_SECRET
          value: "secret/dev/forter-gist/client_secret"
      ports:
        - port: 6157
          protocol: TCP
      healthCheck:
        httpGet:
          path: /healthcheck
          port: 6157
      volumeMounts:
        - mountPath: /tmp
          name: tmp
      resources:
        limits:
          cpu: 1000m
          memory: 400Mi
        requests:
          cpu: 1000m
          memory: 400Mi
